version: 0.2
phases:
  install:
    commands:
      - aws s3 cp models/ s3://ai-themcilroy-models/ --recursive
      - npm install -g serverless
      - cd static
      - npm install
  pre_build:
    commands:
      - echo "pre-build"
  build:
    commands:
      - npm run-script build
  post_build:
    commands:
      - serverless deploy --stage dev