service: ai-site-model-api

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: index.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-west-2

functions:
  app:
    handler: wsgi.handler
    layers:
      - arn:aws:lambda:us-west-2:824269988929:layer:ml-layer:1
    events:
      - http: 'ANY /'
      - http: 'ANY {proxy+}'